---
- hosts: all
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes

    # Too long to run for the purpose of a demonstration
    # and not particularly safe as a raw task.
    # - name: Install pending security updates
    #   raw: sudo unattended-upgrade -d

- hosts: origin
  tasks:
    - name: Ensure nginx is at the latest version
      apt: name=nginx state=latest

    # - name: Copy nginx config
    #   copy:
    #     src:
    #     dest:

    - name: Copy customised index page
      copy:
        src: ./resources/index.html
        dest: /var/www/html/index.nginx-debian.html

    - name: start nginx
      service:
        name: nginx
        state: started

- hosts: edges
  tasks:
    - name: Ensure varnish is installed and latest
      apt: name=varnish state=latest

    - name: Copy varnish config
      copy:
        src: ./varnish/default.vcl
        dest: /etc/varnish/default.vcl

    - name: start varnish
      service:
        name: varnish
        state: started
